Askanser/Askanser.Web/ViewModels/AnswerViewModel.cs
using Askanser.Core.Entities;
using System.ComponentModel.DataAnnotations;

namespace Askanser.Web.ViewModels
{
    public class AnswerViewModel
    {
        [Required]
        [Display(Name = "Question")]
        public Question Question { get; set; }

        [Required]
        [Display(Name = "Text")]
        [StringLength(150, ErrorMessage = "The {0} must be at least {2} characters long. And less then {1}", MinimumLength = 4)]
        public string Text { get; set; }

    }
}

Askanser/Askanser.Web/ViewModels/AskViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Askanser.Web.ViewModels
{
    public class AskViewModel
    {
        [Required]
        [Display(Name = "Text")]
        [StringLength(150, ErrorMessage = "The {0} must be at least {2} characters long. And less then {1}", MinimumLength = 4)]
        public string Text { get; set; }

    }
}

Askanser/Askanser.Web/Controllers/AskanserController.cs
using Askanser.Core.Interfaces;
using Askanser.Web.ViewModels;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Askanser.Web.Controllers
{
    [Authorize]
    public class AskanserController : Controller
    {
        IAskanserProvider askanserManager;

        public AskanserController(IAskanserProvider askanserProvider)
        {
            askanserManager = askanserProvider;
        }

        public ActionResult Index()
        {
            //ViewBag.Questions = new List<Question>(new Question[] { new Question { Id = 0, Text = "Que1" }, new Question { Id = 1, Text = "Que2" }, new Question { Id = 2, Text = "Que3" } });
            return RedirectToAction("Questions");
        }

        [AllowAnonymous]
        public ActionResult TopOneQuanswer()
        {
            ViewBag.TopQuanswer = askanserManager.GetTopOneQuanswer();
            return PartialView();
        }


        public ActionResult Questions()
        {
            //ViewBag.Questions = new List<Question>(new Question[] { new Question { Id = 0, Text = "Que1" }, new Question { Id = 1, Text = "Que2" }, new Question { Id = 2, Text = "Que3" } });
            ViewBag.Questions = askanserManager.GetQuestions();
            return View();
        }



        public ActionResult Answer(int id)
        {
            AnswerViewModel model = new AnswerViewModel()
            {
                Question = askanserManager.GetQuestion(id)
            };

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Answer(AnswerViewModel RedeemModel)
        {
            if (ModelState.IsValid)
            {
                //insert db call here
                // нужно сделать коммон с юзерайди для квесшена, и еще как то что бы ID сюда пришло tempdata вроде должен работать, но вопрос с юзерайди вопроса остаетс яоткрытым
                // кстати еще тебе нужно сделать оценку чужих ответов, и просмотр своих ответов(???)


                bool flag = askanserManager.AddAnswer(RedeemModel.Question.Id, RedeemModel.Text, this.User.Identity.GetUserId());
                if (flag) return Redirect("/");

            }

            return View(RedeemModel);
        }



        public ActionResult Ask()
        {
            //ViewBag.Questions = new List<Question>(new Question[] { new Question { Id = 0, Text = "Que1" }, new Question { Id = 1, Text = "Que2" }, new Question { Id = 2, Text = "Que3" } });
            return View();
        }

        public ActionResult AnswersToMyQuestions()
        {
            ViewBag.Quanswers = askanserManager.GetAnswersForMyQuestions(this.User.Identity.GetUserId());

            return View();
        }


        public ActionResult MyAnswers()
        {
            ViewBag.Quanswers = askanserManager.GetMyAnswers(this.User.Identity.GetUserId());
            return View();
        }

        public ActionResult SetScore(int id)
        {

            QuanswerViewModel model = new QuanswerViewModel()
            {
                Quanswer = askanserManager.GetAnswerForMyQuestion(id)
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SetScore(QuanswerViewModel RedeemModel)
        {
            if (ModelState.IsValid)
            {


                bool flag = askanserManager.SetScore(RedeemModel.Quanswer.AnsId, RedeemModel.Score);
                if (flag) return Redirect("/");

            }

            return View(RedeemModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Ask(AskViewModel model)
        {
            if (ModelState.IsValid)
            {
                //insert db call here
                bool flag = askanserManager.AddQuestion(model.Text, this.User.Identity.GetUserId());
                if (flag) return Redirect("/");
            }

            return View(model);
        }
    }
}

Askanser/Askanser.Web/Views/Askanser/Answer.cshtml
@using Askanser.Web.ViewModels
@using Askanser.Core.Entities

@model Askanser.Web.ViewModels.AnswerViewModel

@{
    ViewBag.Title = "Answer";
}

<div class="container">
    <section>
        @using (Html.BeginForm("Answer", "Askanser", FormMethod.Post, new { @class = "form-horizontal", role = "form", RedeemModel = Model }))
    {
        @Html.HiddenFor(m => m.Question.Text)
        @Html.HiddenFor(m => m.Question.Id)

        @Html.AntiForgeryToken()

        <div class="h2">
            Question:
            @Html.DisplayFor(m => m.Question.Text)?
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.Text, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.Text, new { @class = "form-control row" })
                @Html.ValidationMessageFor(m => m.Text, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Answer" class="btn btn-default" />
            </div>
        </div>
}
    </section>
</div>

Askanser/Askanser.Web/Views/Askanser/AnswersToMyQuestions.cshtml
@using Askanser.Core.Entities
@{
    ViewBag.Title = "Answers";
}

<div class="container">
    <h2>
        Answers to my questions
    </h2>
    <a href="/Askanser/MyAnswers" class="btn btn-default">Lets see if someone scored your answers</a>
    @{
        if ((ViewBag.Quanswers as List<Quanswer>).Count == 0)
        {
            <div class="h3">Looks like nobody has answered your questions yet. You can refresh the page, but I doubt that it'll work. Go ahead, get your self a cup of coffee, and come in 5 minutes </div>
            <div style="font-size: 10px;color: lightgray">ptsss, you can register as another user and answer your own questions and act like it's somebody else..</div>

        }
        else
        {

        <table class="table table-hover">
            <thead>
                <tr>
                    <th style="overflow:hidden">Id</th>
                    <th style="overflow:hidden">Text</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var x in (ViewBag.Quanswers as List<Quanswer>))
                {
                    <tr onclick="window.location='/Askanser/SetScore/@x.AnsId';">
                        <td style="overflow:hidden">@x.QueText</td>
                        <td style="overflow:hidden">@x.AnsText</td>
                    </tr>
                }
            </tbody>
        </table>
        }
    }
        </div>

Askanser/Askanser.Web/Views/Askanser/Ask.cshtml
@using Askanser.Web.ViewModels
@model Askanser.Web.ViewModels.AskViewModel

@{
    ViewBag.Title = "Ask";
}

<div class="container">

    <section>
        <div class="h2">Ask something:</div>
        @using (Html.BeginForm("Ask", "Askanser", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.Text, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.Text, new { @class = "form-control row" })
                @Html.ValidationMessageFor(m => m.Text, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ask" class="btn btn-default" />
            </div>
        </div>
}
    </section>
</div>

Askanser/Askanser.Web/Views/Askanser/MyAnswers.cshtml
@using Askanser.Core.Entities
@{
    ViewBag.Title = "Answers";
}

<div class="container">
    <h2>My Answers</h2>
    <a href="/Askanser/AnswersToMyQuestions" class="btn btn-default">Lets see who answered your questions</a>
    @{ if ((ViewBag.Quanswers as List<Quanswer>).Count == 0)
        {
            <div class="h3">Looks like nobody has scored your answers yet. You can refresh the page, but I doubt that somebody has scored your answer like right now. Go ahead, get your self a cup of coffee, and come in 5 minutes </div>
            <div style="font-size: 10px;color: lightgray">ptsss,  you can register as another user and answer your own questions then log back, grade that answer, then log one more time and see the grade, and act like somebody else done it..</div>

        }
        else
        {
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th style="overflow:hidden">Question</th>
                        <th style="overflow:hidden">Answer</th>
                        <th style="width:20px">Score</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var x in (ViewBag.Quanswers as List<Quanswer>))
                    {
                        <tr>
                            <td style="overflow:hidden">@x.QueText</td>
                            <td style="overflow:hidden">@x.AnsText</td>
                            <td>@x.Score</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    }
</div>

Askanser/Askanser.Web/Views/Askanser/Questions.cshtml
@using Askanser.Core.Entities
@{
    ViewBag.Title = "Answer";
}

<div class="container">
    <h2>
        Damn son, look at what u can answer...
    </h2>
    <a href="/Askanser/Ask" class="btn btn-default">Ask something, I dare you, I double dare you.</a>

    <table class="table table-hover">
        <thead>
            <tr>
                <th width="20px">Id</th>
                <th style="max-width:900px;overflow:hidden">Text</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var x in (ViewBag.Questions as List<Question>))
            {
                <tr onclick="window.location='/Askanser/Answer/@x.Id';">
                    <td width="20px">@x.Id</td>
                    <td style="max-width:900px;overflow:hidden">@x.Text</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Askanser/Askanser.Web/Views/Askanser/SetScore.cshtml
@using Askanser.Web.ViewModels
@using Askanser.Core.Entities

@model Askanser.Web.ViewModels.QuanswerViewModel

@{
    ViewBag.Title = "Set Score";
}

<div class="container">
    <section>
        @using (Html.BeginForm("SetScore", "Askanser", FormMethod.Post, new { @class = "form-horizontal", role = "form", RedeemModel = Model }))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(m => m.Quanswer.AnsId)
        @Html.HiddenFor(m => m.Quanswer.QueText)
        @Html.HiddenFor(m => m.Quanswer.AnsText)
        @Html.HiddenFor(m => m.Quanswer.Score)

        <div class="h2">
            Question:
            @Html.DisplayFor(m => m.Quanswer.QueText)?
        </div>

        <div class="h2">
            Answer:
            @Html.DisplayFor(m => m.Quanswer.AnsText) .
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.Score, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.Score, new { @class = "form-control row" })
                @Html.ValidationMessageFor(m => m.Score, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Answer" class="btn btn-default" />
            </div>
        </div>
}
    </section>
</div>

Askanser/Askanser.Web/Views/Askanser/TopOneQuanswer.cshtml
@using Askanser.Core.Entities

<div class="container">
    @{
        Quanswer q = ViewBag.TopQuanswer as Quanswer;

        <div class="lead">Question: @q.QueText?</div>
        <div class="lead">Answer: @q.AnsText .</div>
        <div class="lead right">Score: @q.Score</div>
    }
</div>